In Flutter you can capture any exception object that you caught:

```dart
try {
  throw null;
} catch (error, stackTrace) {
  await sentry.captureException(
    exception: error,
    stackTrace: stackTrace,
  );
}
```
