```elixir
try do
  raise "This is a test!"
rescue
  exception ->
    Sentry.capture_exception(exception, stacktrace: __STACKTRACE__)
end
```
