## Connect Errors with Spans

Sentry errors can be linked with transactions and spans.

<PlatformSection supported={["java"]} notSupported={["android", "java.spring", "java.spring-boot"]}>

<Note>

We have dedicated performance features for our [Spring](/platforms/java/guides/spring/) and [Spring Boot](/platforms/java/guides/spring-boot/) integrations. In addition, errors are linked with spans automatically using either of these integrations.

</Note>

</PlatformSection>

Errors reported to Sentry while transaction or span is running are linked automatically:

```java {tabTitle:Java}
import io.sentry.Sentry;
import io.sentry.ISpan;

ISpan span = Sentry.startTransaction("task");
try {
  processItem();
} catch (Exception e) {
  Sentry.captureException(e);
} finally {
  span.finish();
}
```

```kotlin {tabTitle:Kotlin}
import io.sentry.Sentry

val span = Sentry.startTransaction("task")
try {
  processItem()
} catch (e: Exception) {
  Sentry.captureException(e)
} finally {
  span.finish()
}
```

Exceptions may be thrown within spans that can finish before exception gets reported to Sentry. To attach span information to this exception, you must link it by calling setThrowable method:

```java {tabTitle:Java}
import io.sentry.Sentry;
import io.sentry.ISpan;

ISpan span = Sentry.getSpan();
if (span == null) {
  span = Sentry.startTransaction("task");
}
try {
  processItem();
} catch (Exception e) {
  span.setThrowable(e);
  throw e;
} finally {
  span.finish();
}
```

```kotlin {tabTitle:Kotlin}
import io.sentry.Sentry

val span = Sentry.getSpan()?: Sentry.startTransaction("task")
try {
  processItem()
} catch (e: Exception) {
  span.throwable = e
  throw e
} finally {
  span.finish()
}
```
